---
# tasks file for liferaydxp
#Installer packages...
- name: install packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - unzip
    - java 
    - vim
    - yum-utils
    - firewalld # Dependence to start docker
#Add repo de docker
- name: Add repo docker
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
#Install Docker
- name: Install docker
  yum:
    name: docker-ce
    state: latest
#Start and enable Docker
- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: yes
#Create user liferay
- name: Create user liferay
  user:
    name: liferay
    group: "{{ item }}" #Add in group docker and wheel
    append: yes
  with_items:
    - docker
    - wheel
# Add user liferay in sudoers
- name: Add user liferay in sudoers
  lineinfile:
    path: /etc/sudoers
    line: 'liferay        ALL=(ALL)       NOPASSWD: ALL'
#Install Docker-compose
- name: Install Docker-compose
  command: "{{ item }}"
  args:
    chdir: $path 
  environment:
    path: /home/ec2-user
  loop:
    - curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
  register: command_output
#Show output
- name: print output
  debug: 
    var=command_output 
